[package]
name = "rsfbclient-diesel"
version = "0.13.0"
description = "The Firebird Diesel implementation"
authors = ["Luis Fernando Batels <luisfbatels@gmail.com>"]
edition = "2018"
repository = "https://github.com/fernandobatels/rsfbclient"
keywords = ["firebird", "fbclient", "database", "ffi"]
categories = ["database"]
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.0", git = "https://github.com/fernandobatels/diesel" }
rsfbclient = { version = "0.14.0", path = "../", default-features = false }
byteorder = "1.0"
bytes = "0.6.0"
chrono = { version = "0.4.19", optional = true }

[features]
default = ["linking"]
dynamic_loading = ["date_time", "rsfbclient/dynamic_loading"]
linking = ["date_time", "rsfbclient/linking"]
pure_rust = ["date_time", "rsfbclient/pure_rust"]
date_time = ["chrono", "rsfbclient/date_time", "diesel/chrono"]

[package.metadata.docs.rs]
all-features = true
