[package]
name = "rsfbclient-diesel"
version = "0.12.0"
description = "The Firebird Diesel implementation"
authors = ["Luis Fernando Batels <luisfbatels@gmail.com>"]
edition = "2018"
repository = "https://github.com/fernandobatels/rsfbclient"
keywords = ["firebird", "fbclient", "database", "ffi"]
categories = ["database"]
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.0", git = "https://github.com/fernandobatels/diesel", features = ["no-default-stmt-impl"] }
rsfbclient = { version = "0.12.0", path = "../" }
rsfbclient-native = { version = "0.12.0", path = "../rsfbclient-native" }
byteorder = "1.0"
bytes = "0.6.0"
