[package]
name = "r2d2_firebird"
version = "0.14.0"
description = "Firebird support for the r2d2 connection pool"
authors = ["silvioprog <silvioprog@gmail.com>", "Jairo H Wiethan <jairinhowiethan@gmail.com>"]
edition = "2018"
repository = "https://github.com/fernandobatels/rsfbclient"
keywords = ["firebird", "sql", "pool", "database"]
categories = ["database"]
license = "MIT"

[dependencies]
rsfbclient = { version = "0.14" }
rsfbclient-core = { version = "0.14" }
r2d2 = { version = "0.8" }
